"""add colums uitem

Revision ID: 70d147f95888
Revises: 04c2fc6996e6
Create Date: 2024-12-05 09:11:45.055078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70d147f95888'
down_revision: Union[str, None] = '04c2fc6996e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_item', sa.Column('film_noir', sa.String(), nullable=True))
    op.drop_column('u_item', 'film_Noir')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_item', sa.Column('film_Noir', sa.VARCHAR(), nullable=True))
    op.drop_column('u_item', 'film_noir')
    # ### end Alembic commands ###
