"""add tables

Revision ID: 8394196cdd87
Revises: a241654c3903
Create Date: 2024-12-02 13:54:44.345711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8394196cdd87'
down_revision: Union[str, None] = 'a241654c3903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('u_data', sa.Column('user_id', sa.String(), nullable=True))
    op.add_column('u_data', sa.Column('item_id', sa.String(), nullable=True))
    op.add_column('u_data', sa.Column('rating', sa.String(), nullable=True))
    op.add_column('u_data', sa.Column('timestamp', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('u_data', 'timestamp')
    op.drop_column('u_data', 'rating')
    op.drop_column('u_data', 'item_id')
    op.drop_column('u_data', 'user_id')
    # ### end Alembic commands ###
