"""add tables

Revision ID: a241654c3903
Revises: 
Create Date: 2024-12-02 10:45:20.799871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a241654c3903'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('u_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_u_data_id'), 'u_data', ['id'], unique=False)
    op.create_table('u_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_u_item_id'), 'u_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_u_item_id'), table_name='u_item')
    op.drop_table('u_item')
    op.drop_index(op.f('ix_u_data_id'), table_name='u_data')
    op.drop_table('u_data')
    # ### end Alembic commands ###
